name: math_keyboard
description: >-2
  Math expression editing using an on-screen software keyboard or physical keyboard input in a
  typeset input field in Flutter.
version: 0.2.1
homepage: https://github.com/simpleclub/math_keyboard/tree/main/math_keyboard

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_math_fork:
    git:
      url: https://github.com/The-Redhat/flutter_math_fork.git
      ref: add_missing_import_to_gesture_detector_builder_selectable.dart
  holding_gesture: ^1.1.0
  intl: ^0.18.0
  math_expressions: ^2.1.0
  petitparser: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  fonts:
  - family: CustomKeyIcons
    fonts:
    - asset: fonts/CustomKeyIcons.ttf

screenshots:
  - description: 'Example of math keyboard on mobile and desktop.'
    path: example/screenshots/mobile_and_desktop.png
  - description: 'Example video showing how to interact with math keyboard.'
    path: example/screenshots/math_keyboard.gif
  - description: 'Example of math keyboard on mobile.'
    path: example/screenshots/mobile.png
  - description: 'Example of math keyboard on desktop.'
    path: example/screenshots/desktop.png
  - description: 'Example of math keyboard functions.'
    path: example/screenshots/functions.png
