name: example
description: Example app showing how to use the math_keyboard package.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  simpleclub_math_keyboard:
    path: ../

flutter:
  uses-material-design: true
