name: math_keyboard_demo
description: Demo app for the math_keyboard package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.5

  math_keyboard:
    path: ../math_keyboard

  url_launcher: ^6.1.4
  url_strategy: ^0.2.0

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
