name: math_keyboard_demo
description: Demo app for the math_keyboard package.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.5

  math_keyboard:
    path: ../math_keyboard

  url_launcher: ^6.1.4
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
