name: greetings

on:
  # Cannot run the greeting job on PRs because the contributors we want to greet will open PRs
  # from their own forks. When creating a PR from a fork, the GitHub Actions associated with that
  # PR will be run from the fork as far as credentials are concerned. The GITHUB_TOKEN secret
  # only has read access in that case and therefore cannot create a PR comment with the greetings
  # message. See:
  # https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token
#  - pull_request
  - issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi ğŸ‘‹ğŸ½ Thank you for opening your first issue with simpleclub/math_keyboard â¤

          You can expect triage from us soon ğŸ™‚
          In the meantime, you can try to search for similar issues in our [issue database].

          [issue database]: https://github.com/simpleclub/math_keyboard/issues?q=is%3Aissue
